### ISSUE TITLE
ConfigurationError: ('Unknown directive', u'http://namespaces.plone.org/plone', u'tile')

### ISSUE THREAD

**Issue by robbuh** [plone/plone.app.debugtoolbar#18]
Plone 5.1.2 
at the start of a client `ConfigurationError: ('Unknown directive', u'http://namespaces.plone.org/plone', u'tile')` error appear

Adding the two lines below fix the issue for me

`vi plone.app.debugtoolbar-1.1.4-py2.7.egg/plone/app/debugtoolbar/browser/configure.zcml`

    <include package="plone.tiles" />
    <include package="plone.app.tiles" />

**Comment by daggelpop** [comment]
I have had the same error, also with Plone 5.1.2 and plone.app.debugtoolbar 1.1.4.

The aforementioned fix did the trick.

**Comment by idgserpro** [comment]
Maybe we can even [use a `zcml:condition`](https://docs.plone.org/develop/addons/components/zcml.html#examples) in the `include` directive if someone is still using Plone 4.

**Comment by petschki** [comment]
Just got the same for Plone 6.0 if plone.app.standardtiles is installed ... see fix #29
