### ISSUE TITLE
upate release - please :)

### ISSUE THREAD

**Issue by iham** [plone/plone.app.debugtoolbar#22]
i experienced troubles with p.a.dtb when using v1.1.4 on a plone5.2 (i know, this is currently "only" a pending release)

where the line
```python
self.appInfo = self.context.getPhysicalRoot()['Control_Panel']
```

this seems to be fixed in the master branch and i can use it with plone5.2 without errors so far.

can somebody make an egg-release on pypi, or are there other issues too?
i ask as this package is stated to be working with plone 5.2 according to pypi.
with that minor update, this would be true ;)

thank you!

**Comment by gforcada** [comment]
1.2.0 is out :tada:
